### ISSUE TITLE
genetic_sampler exception if file already exists

### ISSUE THREAD

**Issue by BrianErikson** [7yl4r/LifeGenes#22]
genetic_sampler crashes to stack trace if you save a cell sample that already exists and then cancelling the tkinter window.

**Comment by BrianErikson** [comment]
Had cellPallete return a boolean depending on if the save was successful or not, which genetic_sampler uses to determine whether to quit the tkinter frame or not. If the save is not successful, the user is notified through the Golly text ribbon.

**Comment by 7yl4r** [comment]
Sounds like a good way to do it. Awesome. =)
